#!/usr/bin/env bash
# House style enforcement. Runs as step one of every test run.
#
# Two rules, both non negotiable:
#   1. No em dashes or en dashes anywhere in tracked source.
#   2. No secrets in tracked files.
#
# Vendored theme submodules under site/themes are third party code and are
# exempt from the dash rule. We do not edit them, so their punctuation is not
# ours to police.

set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

fails=0

note() { printf '  %s\n' "$1"; }
pass() { printf '\033[32mPASS\033[0m  %s\n' "$1"; }
fail() { printf '\033[31mFAIL\033[0m  %s\n' "$1"; fails=$((fails + 1)); }

# Files we actually own. Excludes vendored themes, build output and git internals.
owned_files() {
  git ls-files 2>/dev/null | grep -v '^site/themes/' || true
}

# ---------------------------------------------------------------- dash rule
# The pattern is built from Unicode escapes on purpose. If the literal
# characters appeared in this file, the checker would flag itself.
EM_DASH=$'\u2014'
EN_DASH=$'\u2013'
DASH_CLASS="[${EM_DASH}${EN_DASH}]"

check_dashes() {
  local hits
  hits=$(owned_files | while read -r f; do
    [ -f "$f" ] || continue
    grep -Il . "$f" >/dev/null 2>&1 || continue   # skip binaries
    grep -Hn "$DASH_CLASS" "$f" 2>/dev/null || true
  done)

  if [ -n "$hits" ]; then
    fail "em or en dashes found"
    echo "$hits" | head -20 | while read -r l; do note "$l"; done
  else
    pass "no em dashes or en dashes"
  fi
}

# -------------------------------------------------------------- secret rule
# Catches the shapes that actually leak: real assignments to sensitive keys.
# Placeholder values in .env.example are allowed, that file exists to be a template.
check_secrets() {
  local hits
  hits=$(owned_files | grep -v '\.env\.example$' | while read -r f; do
    [ -f "$f" ] || continue
    grep -Il . "$f" >/dev/null 2>&1 || continue
    grep -HnEi \
      '(password|passwd|secret|api[_-]?key|auth[_-]?token|access[_-]?token)[[:space:]]*[=:][[:space:]]*["'"'"']?[A-Za-z0-9/+_-]{12,}' \
      "$f" 2>/dev/null \
      | grep -vEi '(changeme|example|placeholder|your[_-]|xxx|\$\{|<[a-z_]+>|REPLACE|TODO|generated by|openssl rand)' || true
  done)

  if [ -n "$hits" ]; then
    fail "possible secret committed"
    echo "$hits" | head -10 | while read -r l; do note "$l"; done
  else
    pass "no secrets in tracked files"
  fi
}

# .env must never be tracked, regardless of what .gitignore claims.
check_env_untracked() {
  if git ls-files --error-unmatch .env >/dev/null 2>&1; then
    fail ".env is tracked by git and must not be"
  else
    pass ".env is not tracked"
  fi
}

echo "Style and secret checks"
echo "-----------------------"
check_dashes
check_secrets
check_env_untracked
echo

if [ "$fails" -gt 0 ]; then
  echo "check-style: $fails check(s) failed"
  exit 1
fi
echo "check-style: all checks passed"
