#!/usr/bin/env bash
# Generate .env with fresh random secrets.
#
# Secrets are written straight to the file and never printed, so they cannot
# leak into terminal scrollback, CI logs or a chat transcript.

set -euo pipefail
cd "$(dirname "$0")/.." || exit 1

if [ -f .env ] && [ "${1:-}" != "--force" ]; then
  echo "init-env: .env already exists. Use --force to regenerate."
  echo "init-env: regenerating invalidates the current Postgres password, so"
  echo "          you would also need to drop the postgres volume."
  exit 1
fi

gen() { openssl rand -base64 24 | tr -d '/+=' | head -c 32; }

umask 077   # .env is created readable only by you
{
  echo "# Generated by scripts/init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Secrets in this file are real. It is gitignored. Do not commit or paste it."
  echo
  echo "POSTGRES_USER=listmonk"
  echo "POSTGRES_PASSWORD=$(gen)"
  echo "POSTGRES_DB=listmonk"
  echo
  echo "LISTMONK_ADMIN_USER=admin"
  echo "LISTMONK_ADMIN_PASSWORD=$(gen)"
  echo
  echo "SITE_URL=${SITE_URL:-http://localhost:8080}"
  echo "LISTMONK_LIST_UUID="
} > .env

echo "init-env: wrote .env with generated secrets (mode $(stat -c %a .env))"
echo "init-env: read the admin password with:  grep LISTMONK_ADMIN_PASSWORD .env"
